name: Build/Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo snap install --classic astral-uv
          sudo snap install shfmt
          sudo snap install shellcheck
      - name: Run linters
        run: make lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo snap install --classic astral-uv
          sudo snap install shfmt
          sudo snap install shellcheck
      - name: Run tests
        run: make unit

